### ISSUE TITLE
console.log usage

### ISSUE THREAD

**Issue by alexgorbatchev** [m59peacemaker/node-try-net-connect#4]
I think using console.log to for testing is not a good pattern. I'd love to clean this up a bit if you accept #3 and #2.

**Comment by m59peacemaker** [comment]
See #1. I'm thinking of getting rid of the console logs. They shouldn't be a concern of this module. I'm thinking of just removing the logs and emitting `retry`. The consumer of the module should log whatever they want using the callback or retry event. Agreed?

**Comment by alexgorbatchev** [comment]
Yes, that would be ideal solution I think. Do you have any thoughts on when you want to do this?
